@echo off
echo 🚀 正在启动 厦大_JiaYuan RAG 系统...

:: 启动后端 (打开新窗口并保持开启)
echo 启动后端核心引擎...
start cmd /k "cd backend && python main.py"

:: 启动前端 (打开新窗口并保持开启)
echo 启动前端交互界面...
start cmd /k "cd frontend && npm run dev"

echo ✅ 启动命令已发送！请等待黑色窗口出现 Application startup complete...